name: Continuous Integration

# This action works with pull requests and pushes
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Install flake8
      #   run: pip install flake8
      - name: Run flake8
        run: |
          flake8 . 
      
      - name: Running Test
        run: |
          python manage.py test 


# databases:
#   - name: productionDatabase
#     databaseName: productionDatabase
#     user: ziemieu

# services:
#   - type: web
#     name: productionDatabase
#     env: python
#     buildCommand: "./build.sh"
#     startCommand: "gunicorn myproject.wsgi:application"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: productionDatabase
#           property: connectionString
#       - key: SECRET_KEY
#         generateValue: true
#       - key: WEB_CONCURRENCY
#         value: 4
